Refactor Tekton Tasks input params, drop unused values
Signed-off-by: avasilev <avasilev@redhat.com>

diff --git a/config/forge/resolve_job.yaml b/config/forge/resolve_job.yaml
--- a/config/forge/resolve_job.yaml
+++ b/config/forge/resolve_job.yaml
@@ -19,13 +19,12 @@ spec:
         - name: resolve
           imagePullPolicy: Always
           env:
-            - name: FOURNOS_JOB_NAME
+            - name: FJOB_NAME
             - name: FOURNOS_NAMESPACE
-            - name: FORGE_PROJECT
-            - name: FORGE_CONFIG
-            - name: FOURNOS_ENV
             - name: FOURNOS_STEP
               value: resolve-fournos-config
+            - name: FOURNOS_CI
+              value: "true"
           command: ["/bin/bash", "-c"]
           args:
             - |
@@ -39,20 +38,24 @@ spec:
 
               exec &> >(tee -a "$ARTIFACT_DIR/run.log")
 
-              cat > $ARTIFACT_DIR/forge_config.yaml <<< "$FORGE_CONFIG"
+              oc get "fjob/$FJOB_NAME" -n "$FOURNOS_NAMESPACE" -oyaml > $ARTIFACT_DIR/fournos_fjob.yaml
 
-              cat > $ARTIFACT_DIR/forge_config.env <<< "$FOURNOS_ENV"
-
-              if grep -q '^PULL_BASE_SHA=' $ARTIFACT_DIR/forge_config.env; then
-                export PULL_BASE_SHA=$(cat $ARTIFACT_DIR/forge_config.env | grep '^PULL_BASE_SHA=' | cut -d'=' -f2)
+              PULL_BASE_SHA=$(cat "$ARTIFACT_DIR/fournos_fjob.yaml" | yq -r .spec.env.PULL_BASE_SHA)
+              if [[ "$PULL_BASE_SHA" != null ]]; then
+                export PULL_BASE_SHA
+              else
+                unset PULL_BASE_SHA
               fi
 
-              if grep -q '^PULL_PULL_SHA=' $ARTIFACT_DIR/forge_config.env; then
-                export PULL_PULL_SHA=$(cat $ARTIFACT_DIR/forge_config.env | grep '^PULL_PULL_SHA=' | cut -d'=' -f2)
+              PULL_PULL_SHA=$(cat "$ARTIFACT_DIR/fournos_fjob.yaml" | yq -r .spec.env.PULL_PULL_SHA)
+              if [[ "$PULL_PULL_SHA" != null ]]; then
+                export PULL_PULL_SHA
+              else
+                unset PULL_PULL_SHA
               fi
 
               if [[ "${PULL_PULL_SHA:-}" ]]; then
-              echo
+                echo
                 echo "Updating to PULL_PULL_SHA=$PULL_PULL_SHA ..."
 
                 git -C "$FORGE_HOME" fetch --quiet origin "$PULL_PULL_SHA"
@@ -60,8 +63,13 @@ spec:
               else
                 echo "No PULL_PULL_SHA, using the image commit"
               fi
-
               git show --quiet
+
+              FORGE_PROJECT=$(cat "$ARTIFACT_DIR/fournos_fjob.yaml" | yq -r .spec.forge.project)
+              if [[ -z "$FORGE_PROJECT" || "$FORGE_PROJECT" == null ]]; then
+                echo "ERROR: invalid .spec.forge.project='$FORGE_PROJECT' in $FOURNOS_NAMESPACE/$FJOB_NAME"
+                exit 1
+              fi
 
               export FOURNOS_CI=true
 
